[project]
name = "3mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "mlflow>=3.3.1",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
]
